修复src变化后，预览框中图片地址未更新的问题
wszxdhr/vue-directive-image-previewer pull request #10
Opened 2019-09-04 12:06 UTC by zhangyufen

大哥，你瞅瞅代码有没有问题吧

2019-09-04 12:09 UTC, zhangyufen commented
> 大哥，你瞅瞅代码有没有问题吧

我就是把同样的代码在update 操作里 也执行了一遍。  因为bind 钩子和 update钩子都执行同样的操作，就用了这个简写方式

<img width="790" alt="WechatIMG1704" src="https://user-images.githubusercontent.com/14355473/64253442-e7cf4f80-cf4f-11e9-9ec6-985bc922988a.png">

2019-09-04 12:12 UTC, wszxdhr commented
妥了兄弟
本来这玩意我是重构了的，结果后来翻车住院去了，最近实在太忙没时间写握草
等有空把手头这个写完推一波，应该能比现在这个好点


话说你都是啥项目在用啊，我一直以为这野生Repository都没人用




在2019年09月4日 20:09，zhangyfuen<notifications@github.com> 写道：

大哥，你瞅瞅代码有没有问题吧

我就是把同样的代码在update 操作里 也执行了一遍。 因为bind 钩子和 update钩子都执行同样的操作，就用了这个简写方式

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.

2019-09-04 12:17 UTC, zhangyufen commented
> 妥了兄弟 本来这玩意我是重构了的，结果后来翻车住院去了，最近实在太忙没时间写握草 等有空把手头这个写完推一波，应该能比现在这个好点 话说你都是啥项目在用啊，我一直以为这野生Repository都没人用 在2019年09月4日 20:09，zhangyfuen<notifications@github.com> 写道： 大哥，你瞅瞅代码有没有问题吧 我就是把同样的代码在update 操作里 也执行了一遍。 因为bind 钩子和 update钩子都执行同样的操作，就用了这个简写方式 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

公司的内部系统，图片特别多，后来需要增加放大预览的功能。我找了一圈，发现你写的这个命令式的组件，用起来最方便，不咋需要改动业务代码就可以用

2019-09-04 12:23 UTC, zhangyufen commented
你这现在身体没事了吧   😁
我已经用了半年才发现有这问题。现在有点着急修复。 既然你后续还要出新版本的，那我先加trick 临时解决下这个问题，后续等你的新版本吧  😄

2019-09-04 12:24 UTC, wszxdhr commented
稳妥，理论上今晚就可以merge之后发版

2019-09-04 12:24 UTC, zhangyufen commented
> 你这现在身体没事了吧 😁
> 我已经用了半年才发现有这问题。现在有点着急修复。 既然你后续还要出新版本的，那我先加trick 临时解决下这个问题，后续等你的新版本吧 😄

如果你有时间能尽快先把这个处理一下 就更好了 😄

2019-09-04 12:25 UTC, zhangyufen commented
好的好的

2019-09-04 12:25 UTC, wszxdhr commented
3.x估计要一阵，目前2.x以修复bug为主，感谢关注哈

2019-09-04 13:11 UTC, wszxdhr requested changes
由于lint标准为standard，因此：
1. 17行function后请加空格
2. 去除22行的分号

2019-09-05 02:56 UTC, zhangyufen commented
> 由于lint标准为standard，因此：
> 
> 1. 17行function后请加空格
> 2. 去除22行的分号

好的，已经改了

2019-09-05 03:00 UTC, merged

2019-09-05 03:01 UTC, wszxdhr commented
已合并，请查收